#ifndef SRC_S21_STRERROR_H_
#define SRC_S21_STRERROR_H_

#if defined(__APPLE__)
#define MAX_ERROR_NUM 106
#define SYS_ERROR_LIST_MAC                                       \
  error[0] = "Undefined error: 0";                               \
  error[1] = "Operation not permitted";                          \
  error[2] = "No such file or directory";                        \
  error[3] = "No such process";                                  \
  error[4] = "Interrupted system call";                          \
  error[5] = "Input/output error";                               \
  error[6] = "Device not configured";                            \
  error[7] = "Argument list too long";                           \
  error[8] = "Exec format error";                                \
  error[9] = "Bad file descriptor";                              \
  error[10] = "No child processes";                              \
  error[11] = "Resource deadlock avoided";                       \
  error[12] = "Cannot allocate memory";                          \
  error[13] = "Permission denied";                               \
  error[14] = "Bad address";                                     \
  error[15] = "Block device required";                           \
  error[16] = "Resource busy";                                   \
  error[17] = "File exists";                                     \
  error[18] = "Cross-device link";                               \
  error[19] = "Operation not supported by device";               \
  error[20] = "Not a directory";                                 \
  error[21] = "Is a directory";                                  \
  error[22] = "Invalid argument";                                \
  error[23] = "Too many open files in system";                   \
  error[24] = "Too many open files";                             \
  error[25] = "Inappropriate ioctl for device";                  \
  error[26] = "Text file busy";                                  \
  error[27] = "File too large";                                  \
  error[28] = "No space left on device";                         \
  error[29] = "Illegal seek";                                    \
  error[30] = "Read-only file system";                           \
  error[31] = "Too many links";                                  \
  error[32] = "Broken pipe";                                     \
  error[33] = "Numerical argument out of domain";                \
  error[34] = "Result too large";                                \
  error[35] = "Resource temporarily unavailable";                \
  error[36] = "Operation now in progress";                       \
  error[37] = "Operation already in progress";                   \
  error[38] = "Socket operation on non-socket";                  \
  error[39] = "Destination address required";                    \
  error[40] = "Message too long";                                \
  error[41] = "Protocol wrong type for socket";                  \
  error[42] = "Protocol not available";                          \
  error[43] = "Protocol not supported";                          \
  error[44] = "Socket type not supported";                       \
  error[45] = "Operation not supported";                         \
  error[46] = "Protocol family not supported";                   \
  error[47] = "Address family not supported by protocol family"; \
  error[48] = "Address already in use";                          \
  error[49] = "Can't assign requested address";                  \
  error[50] = "Network is down";                                 \
  error[51] = "Network is unreachable";                          \
  error[52] = "Network dropped connection on reset";             \
  error[53] = "Software caused connection abort";                \
  error[54] = "Connection reset by peer";                        \
  error[55] = "No buffer space available";                       \
  error[56] = "Socket is already connected";                     \
  error[57] = "Socket is not connected";                         \
  error[58] = "Can't send after socket shutdown";                \
  error[59] = "Too many references: can't splice";               \
  error[60] = "Operation timed out";                             \
  error[61] = "Connection refused";                              \
  error[62] = "Too many levels of symbolic links";               \
  error[63] = "File name too long";                              \
  error[64] = "Host is down";                                    \
  error[65] = "No route to host";                                \
  error[66] = "Directory not empty";                             \
  error[67] = "Too many processes";                              \
  error[68] = "Too many users";                                  \
  error[69] = "Disc quota exceeded";                             \
  error[70] = "Stale NFS file handle";                           \
  error[71] = "Too many levels of remote in path";               \
  error[72] = "RPC struct is bad";                               \
  error[73] = "RPC version wrong";                               \
  error[74] = "RPC prog. not avail";                             \
  error[75] = "Program version wrong";                           \
  error[76] = "Bad procedure for program";                       \
  error[77] = "No locks available";                              \
  error[78] = "Function not implemented";                        \
  error[79] = "Inappropriate file type or format";               \
  error[80] = "Authentication error";                            \
  error[81] = "Need authenticator";                              \
  error[82] = "Device power is off";                             \
  error[83] = "Device error";                                    \
  error[84] = "Value too large to be stored in data type";       \
  error[85] = "Bad executable (or shared library)";              \
  error[86] = "Bad CPU type in executable";                      \
  error[87] = "Shared library version mismatch";                 \
  error[88] = "Malformed Mach-o file";                           \
  error[89] = "Operation canceled";                              \
  error[90] = "Identifier removed";                              \
  error[91] = "No message of desired type";                      \
  error[92] = "Illegal byte sequence";                           \
  error[93] = "Attribute not found";                             \
  error[94] = "Bad message";                                     \
  error[95] = "EMULTIHOP (Reserved)";                            \
  error[96] = "No message available on STREAM";                  \
  error[97] = "ENOLINK (Reserved)";                              \
  error[98] = "No STREAM resources";                             \
  error[99] = "Not a STREAM";                                    \
  error[100] = "Protocol error";                                 \
  error[101] = "STREAM ioctl timeout";                           \
  error[102] = "Operation not supported on socket";              \
  error[103] = "Policy not found";                               \
  error[104] = "State not recoverable";                          \
  error[105] = "Previous owner died";                            \
  error[106] = "Interface output queue is full";
#elif defined(__linux__)
#define MAX_ERROR_NUM 133
#define SYS_ERROR_LIST_LINUX                                       \
  error[0] = "Success";                                            \
  error[1] = "Operation not permitted";                            \
  error[2] = "No such file or directory";                          \
  error[3] = "No such process";                                    \
  error[4] = "Interrupted system call";                            \
  error[5] = "Input/output error";                                 \
  error[6] = "No such device or address";                          \
  error[7] = "Argument list too long";                             \
  error[8] = "Exec format error";                                  \
  error[9] = "Bad file descriptor";                                \
  error[10] = "No child processes";                                \
  error[11] = "Resource temporarily unavailable";                  \
  error[12] = "Cannot allocate memory";                            \
  error[13] = "Permission denied";                                 \
  error[14] = "Bad address";                                       \
  error[15] = "Block device required";                             \
  error[16] = "Device or resource busy";                           \
  error[17] = "File exists";                                       \
  error[18] = "Invalid cross-device link";                         \
  error[19] = "No such device";                                    \
  error[20] = "Not a directory";                                   \
  error[21] = "Is a directory";                                    \
  error[22] = "Invalid argument";                                  \
  error[23] = "Too many open files in system";                     \
  error[24] = "Too many open files";                               \
  error[25] = "Inappropriate ioctl for device";                    \
  error[26] = "Text file busy";                                    \
  error[27] = "File too large";                                    \
  error[28] = "No space left on device";                           \
  error[29] = "Illegal seek";                                      \
  error[30] = "Read-only file system";                             \
  error[31] = "Too many links";                                    \
  error[32] = "Broken pipe";                                       \
  error[33] = "Numerical argument out of domain";                  \
  error[34] = "Numerical result out of range";                     \
  error[35] = "Resource deadlock avoided";                         \
  error[36] = "File name too long";                                \
  error[37] = "No locks available";                                \
  error[38] = "Function not implemented";                          \
  error[39] = "Directory not empty";                               \
  error[40] = "Too many levels of symbolic links";                 \
  error[41] = "Unknown error 41";                                  \
  error[42] = "No message of desired type";                        \
  error[43] = "Identifier removed";                                \
  error[44] = "Channel number out of range";                       \
  error[45] = "Level 2 not synchronized";                          \
  error[46] = "Level 3 halted";                                    \
  error[47] = "Level 3 reset";                                     \
  error[48] = "Link number out of range";                          \
  error[49] = "Protocol driver not attached";                      \
  error[50] = "No CSI structure available";                        \
  error[51] = "Level 2 halted";                                    \
  error[52] = "Invalid exchange";                                  \
  error[53] = "Invalid request descriptor";                        \
  error[54] = "Exchange full";                                     \
  error[55] = "No anode";                                          \
  error[56] = "Invalid request code";                              \
  error[57] = "Invalid slot";                                      \
  error[58] = "Unknown error 58";                                  \
  error[59] = "Bad font file format";                              \
  error[60] = "Device not a stream";                               \
  error[61] = "No data available";                                 \
  error[62] = "Timer expired";                                     \
  error[63] = "Out of streams resources";                          \
  error[64] = "Machine is not on the network";                     \
  error[65] = "Package not installed";                             \
  error[66] = "Object is remote";                                  \
  error[67] = "Link has been severed";                             \
  error[68] = "Advertise error";                                   \
  error[69] = "Srmount error";                                     \
  error[70] = "Communication error on send";                       \
  error[71] = "Protocol error";                                    \
  error[72] = "Multihop attempted";                                \
  error[73] = "RFS specific error";                                \
  error[74] = "Bad message";                                       \
  error[75] = "Value too large for defined data type";             \
  error[76] = "Name not unique on network";                        \
  error[77] = "File descriptor in bad state";                      \
  error[78] = "Remote address changed";                            \
  error[79] = "Can not access a needed shared library";            \
  error[80] = "Accessing a corrupted shared library";              \
  error[81] = ".lib section in a.out corrupted";                   \
  error[82] = "Attempting to link in too many shared libraries";   \
  error[83] = "Cannot exec a shared library directly";             \
  error[84] = "Invalid or incomplete multibyte or wide character"; \
  error[85] = "Interrupted system call should be restarted";       \
  error[86] = "Streams pipe error";                                \
  error[87] = "Too many users";                                    \
  error[88] = "Socket operation on non-socket";                    \
  error[89] = "Destination address required";                      \
  error[90] = "Message too long";                                  \
  error[91] = "Protocol wrong type for socket";                    \
  error[92] = "Protocol not available";                            \
  error[93] = "Protocol not supported";                            \
  error[94] = "Socket type not supported";                         \
  error[95] = "Operation not supported";                           \
  error[96] = "Protocol family not supported";                     \
  error[97] = "Address family not supported by protocol";          \
  error[98] = "Address already in use";                            \
  error[99] = "Cannot assign requested address";                   \
  error[100] = "Network is down";                                  \
  error[101] = "Network is unreachable";                           \
  error[102] = "Network dropped connection on reset";              \
  error[103] = "Software caused connection abort";                 \
  error[104] = "Connection reset by peer";                         \
  error[105] = "No buffer space available";                        \
  error[106] = "Transport endpoint is already connected";          \
  error[107] = "Transport endpoint is not connected";              \
  error[108] = "Cannot send after transport endpoint shutdown";    \
  error[109] = "Too many references: cannot splice";               \
  error[110] = "Connection timed out";                             \
  error[111] = "Connection refused";                               \
  error[112] = "Host is down";                                     \
  error[113] = "No route to host";                                 \
  error[114] = "Operation already in progress";                    \
  error[115] = "Operation now in progress";                        \
  error[116] = "Stale file handle";                                \
  error[117] = "Structure needs cleaning";                         \
  error[118] = "Not a XENIX named type file";                      \
  error[119] = "No XENIX semaphores available";                    \
  error[120] = "Is a named type file";                             \
  error[121] = "Remote I/O error";                                 \
  error[122] = "Disk quota exceeded";                              \
  error[123] = "No medium found";                                  \
  error[124] = "Wrong medium type";                                \
  error[125] = "Operation canceled";                               \
  error[126] = "Required key not available";                       \
  error[127] = "Key has expired";                                  \
  error[128] = "Key has been revoked";                             \
  error[129] = "Key was rejected by service";                      \
  error[130] = "Owner died";                                       \
  error[131] = "State not recoverable";                            \
  error[132] = "Operation not possible due to RF-kill";            \
  error[133] = "Memory page has hardware error";
#else
#define MAX_ERROR_NUM 0
#define SYS_ERROR_LIST_WINDOWS                                    \
  error[0] = "Unknown error";
#endif
#endif  // SRC_S21_STRERROR_H_
